/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/_console'
import { Route as AuthenticatedUnauthorizedRouteImport } from './routes/_authenticated/unauthorized'
import { Route as AuthenticatedConsoleAdminRouteImport } from './routes/_authenticated/_console/admin'
import { Route as AuthenticatedConsoleRolesRouteImport } from './routes/_authenticated/_console/roles'
import { Route as AuthenticatedConsoleUsersRouteImport } from './routes/_authenticated/_console/users'
import { Route as AuthenticatedMachinesIndexRouteImport } from './routes/_authenticated/machines/index'
import { Route as AuthenticatedMachinesMacRouteImport } from './routes/_authenticated/machines/$mac'
import { Route as AuthenticatedViewsViewIdRouteImport } from './routes/_authenticated/views/$viewId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnauthorizedRoute =
  AuthenticatedUnauthorizedRouteImport.update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsoleAdminRoute =
  AuthenticatedConsoleAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleRolesRoute =
  AuthenticatedConsoleRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleUsersRoute =
  AuthenticatedConsoleUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedMachinesIndexRoute =
  AuthenticatedMachinesIndexRouteImport.update({
    id: '/machines/',
    path: '/machines/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMachinesMacRoute =
  AuthenticatedMachinesMacRouteImport.update({
    id: '/machines/$mac',
    path: '/machines/$mac',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedViewsViewIdRoute =
  AuthenticatedViewsViewIdRouteImport.update({
    id: '/views/$viewId',
    path: '/views/$viewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/admin': typeof AuthenticatedConsoleAdminRoute
  '/roles': typeof AuthenticatedConsoleRolesRoute
  '/users': typeof AuthenticatedConsoleUsersRoute
  '/machines/$mac': typeof AuthenticatedMachinesMacRoute
  '/views/$viewId': typeof AuthenticatedViewsViewIdRoute
  '/machines/': typeof AuthenticatedMachinesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/admin': typeof AuthenticatedConsoleAdminRoute
  '/roles': typeof AuthenticatedConsoleRolesRoute
  '/users': typeof AuthenticatedConsoleUsersRoute
  '/machines/$mac': typeof AuthenticatedMachinesMacRoute
  '/views/$viewId': typeof AuthenticatedViewsViewIdRoute
  '/machines': typeof AuthenticatedMachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_console': typeof AuthenticatedConsoleRouteWithChildren
  '/_authenticated/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_console/admin': typeof AuthenticatedConsoleAdminRoute
  '/_authenticated/_console/roles': typeof AuthenticatedConsoleRolesRoute
  '/_authenticated/_console/users': typeof AuthenticatedConsoleUsersRoute
  '/_authenticated/machines/$mac': typeof AuthenticatedMachinesMacRoute
  '/_authenticated/views/$viewId': typeof AuthenticatedViewsViewIdRoute
  '/_authenticated/machines/': typeof AuthenticatedMachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/roles'
    | '/users'
    | '/machines/$mac'
    | '/views/$viewId'
    | '/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/unauthorized'
    | '/admin'
    | '/roles'
    | '/users'
    | '/machines/$mac'
    | '/views/$viewId'
    | '/machines'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_console'
    | '/_authenticated/unauthorized'
    | '/_authenticated/'
    | '/_authenticated/_console/admin'
    | '/_authenticated/_console/roles'
    | '/_authenticated/_console/users'
    | '/_authenticated/machines/$mac'
    | '/_authenticated/views/$viewId'
    | '/_authenticated/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_console': {
      id: '/_authenticated/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/unauthorized': {
      id: '/_authenticated/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthenticatedUnauthorizedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_console/admin': {
      id: '/_authenticated/_console/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedConsoleAdminRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/_console/roles': {
      id: '/_authenticated/_console/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedConsoleRolesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/_console/users': {
      id: '/_authenticated/_console/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedConsoleUsersRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/machines/': {
      id: '/_authenticated/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof AuthenticatedMachinesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/machines/$mac': {
      id: '/_authenticated/machines/$mac'
      path: '/machines/$mac'
      fullPath: '/machines/$mac'
      preLoaderRoute: typeof AuthenticatedMachinesMacRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/views/$viewId': {
      id: '/_authenticated/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/views/$viewId'
      preLoaderRoute: typeof AuthenticatedViewsViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleAdminRoute: typeof AuthenticatedConsoleAdminRoute
  AuthenticatedConsoleRolesRoute: typeof AuthenticatedConsoleRolesRoute
  AuthenticatedConsoleUsersRoute: typeof AuthenticatedConsoleUsersRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleAdminRoute: AuthenticatedConsoleAdminRoute,
  AuthenticatedConsoleRolesRoute: AuthenticatedConsoleRolesRoute,
  AuthenticatedConsoleUsersRoute: AuthenticatedConsoleUsersRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
  AuthenticatedUnauthorizedRoute: typeof AuthenticatedUnauthorizedRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMachinesMacRoute: typeof AuthenticatedMachinesMacRoute
  AuthenticatedViewsViewIdRoute: typeof AuthenticatedViewsViewIdRoute
  AuthenticatedMachinesIndexRoute: typeof AuthenticatedMachinesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
  AuthenticatedUnauthorizedRoute: AuthenticatedUnauthorizedRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMachinesMacRoute: AuthenticatedMachinesMacRoute,
  AuthenticatedViewsViewIdRoute: AuthenticatedViewsViewIdRoute,
  AuthenticatedMachinesIndexRoute: AuthenticatedMachinesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
