/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedMachinesIndexRouteImport } from './routes/_authed/machines/index'
import { Route as AuthedMachinesMacRouteImport } from './routes/_authed/machines/$mac'
import { Route as AuthedViewsViewIdRouteImport } from './routes/_authed/views/$viewId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMachinesIndexRoute = AuthedMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMachinesMacRoute = AuthedMachinesMacRouteImport.update({
  id: '/machines/$mac',
  path: '/machines/$mac',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedViewsViewIdRoute = AuthedViewsViewIdRouteImport.update({
  id: '/views/$viewId',
  path: '/views/$viewId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRoute
  '/machines/$mac': typeof AuthedMachinesMacRoute
  '/views/$viewId': typeof AuthedViewsViewIdRoute
  '/machines/': typeof AuthedMachinesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRoute
  '/': typeof AuthedIndexRoute
  '/machines/$mac': typeof AuthedMachinesMacRoute
  '/views/$viewId': typeof AuthedViewsViewIdRoute
  '/machines': typeof AuthedMachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/machines/$mac': typeof AuthedMachinesMacRoute
  '/_authed/views/$viewId': typeof AuthedViewsViewIdRoute
  '/_authed/machines/': typeof AuthedMachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/machines/$mac'
    | '/views/$viewId'
    | '/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/'
    | '/machines/$mac'
    | '/views/$viewId'
    | '/machines'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/admin'
    | '/_authed/'
    | '/_authed/machines/$mac'
    | '/_authed/views/$viewId'
    | '/_authed/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/machines/': {
      id: '/_authed/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof AuthedMachinesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/machines/$mac': {
      id: '/_authed/machines/$mac'
      path: '/machines/$mac'
      fullPath: '/machines/$mac'
      preLoaderRoute: typeof AuthedMachinesMacRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/views/$viewId': {
      id: '/_authed/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/views/$viewId'
      preLoaderRoute: typeof AuthedViewsViewIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedMachinesMacRoute: typeof AuthedMachinesMacRoute
  AuthedViewsViewIdRoute: typeof AuthedViewsViewIdRoute
  AuthedMachinesIndexRoute: typeof AuthedMachinesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedMachinesMacRoute: AuthedMachinesMacRoute,
  AuthedViewsViewIdRoute: AuthedViewsViewIdRoute,
  AuthedMachinesIndexRoute: AuthedMachinesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
